// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP-mZxxpWRE8oejc25BF6At76qv0Q0ic8',
    appId: '1:772561215621:web:1dc51f01a23c1dd68b09ec',
    messagingSenderId: '772561215621',
    projectId: 'sabidos-fc654',
    authDomain: 'sabidos-fc654.firebaseapp.com',
    storageBucket: 'sabidos-fc654.firebasestorage.app',
    measurementId: 'G-T6L50TVSH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMsMRUNx7Z150P4sLSo8LHZ0KYPLE9Mto',
    appId: '1:772561215621:android:1b7281af06ebb83d8b09ec',
    messagingSenderId: '772561215621',
    projectId: 'sabidos-fc654',
    storageBucket: 'sabidos-fc654.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBejsFYC6Q1fdY8sURWJ1N_-9HE-a7dkP8',
    appId: '1:772561215621:ios:a52781812718749a8b09ec',
    messagingSenderId: '772561215621',
    projectId: 'sabidos-fc654',
    storageBucket: 'sabidos-fc654.firebasestorage.app',
    iosClientId: '772561215621-jmm8g000i81a15lu3c9or4icvkcgg4mo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sabidos2app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBejsFYC6Q1fdY8sURWJ1N_-9HE-a7dkP8',
    appId: '1:772561215621:ios:a52781812718749a8b09ec',
    messagingSenderId: '772561215621',
    projectId: 'sabidos-fc654',
    storageBucket: 'sabidos-fc654.firebasestorage.app',
    iosClientId: '772561215621-jmm8g000i81a15lu3c9or4icvkcgg4mo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sabidos2app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy4S17WlLPW2eR_-ZpANCkX4XN06nYpgs',
    appId: '1:772561215621:web:4b413d1d909d81598b09ec',
    messagingSenderId: '772561215621',
    projectId: 'sabidos-fc654',
    authDomain: 'sabidos-fc654.firebaseapp.com',
    storageBucket: 'sabidos-fc654.firebasestorage.app',
    measurementId: 'G-BVC63J3JNP',
  );
}
