name: sabidos2app
description: De alunos para alunos, SabidoS².
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  provider: ^6.1.5+1
  speech_to_text: ^6.6.0
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  android: true
  ios: true
  web: false

  background_image: "assets/images/SabidosBackgroundSplash.png"
  image: "assets/images/SabidosLogoSplash.png"
  branding: "assets/images/SabidosBrandingSplash.png"

  android_12:
    color: "#0F0E27"
    image: "assets/images/SabidosLogoSplash.png"
    branding: "assets/images/SabidosBrandingSplash.png"
